DEFAULT_NUMBER_OF_PROJECTS = 100

GCP_SERVICES = ["Compute Engine",
"VMWare Engine",
"BigQuery Reservation API",
"Cloud SQL",
"Cloud Storage",
"Cloud Logging",
"GKE Enterprise / GDC",
"BigQuery",
"Networking",
"Notebooks",
"Invoice",
"Cloud Pub/Sub",
"Cloud Composer",
"Cloud Data Fusion",
"Cloud Monitoring",
"Elastic Cloud (Elasticsearch Service)",
"Cloud Dialogflow API",
"Vertex AI",
"Cloud Run",
"Cloud Key Managment Service (KMS)",
"Kubernetes Engine",
"VM Manager",
"Cloud IDS",
"Cloud Memorystore for Redis",
"Dataplex",
"Cloud Dataflow",
"Cloud Filestore",
"NetApp Volumes",
"Manager Service for Microsoft Active Directory",
"Cloud Workstations",
"Cloud DNS",
"Cloud Build",
"Artifact Registry",
"Geocoding API",
"Cloud Spanner",
"Cloud Run Functions",
"Secret Manager",
"Container Registry Vulnerability Scanning",
"Places API",
"Datastream",
"BigQuery Storage API",
"Cloud Machine Learning Engine",
"Cloud Speech API",
"Backup for GKE",
"Vertex AI Search",
"Cloud Scheduler",
"Pub/Sub Lite",
"BigQuery BI Engine",
"Anthos Service Mesh",
"App Engine",
"Data Catalog",
"reCAPTCHA Enterprise",
"Workflows",
"Dataproc"]


PROJECT_ID = "qwiklabs-asl-04-8e9f23e85ced"
DATASET_NAME = "billing_dataset"
TABLE_NAME = "fake_billing_data"
TABLE_FIELDS = [
    {"name": "tla", "datatype": "STRING", "mode": "REQUIRED"},
    {"name": "project_id", "datatype": "STRING", "mode": "REQUIRED"},
    {"name": "environment", "datatype": "STRING", "mode": "REQUIRED"},
    {"name": "service_description", "datatype": "STRING", "mode": "REQUIRED"},
    {"name": "invoice_month", "datatype": "STRING", "mode": "REQUIRED"},
    {"name": "usage_start_time", "datatype": "TIMESTAMP", "mode": "REQUIRED"},
    {"name": "usage_end_time", "datatype": "TIMESTAMP", "mode": "REQUIRED"},
    {"name": "cost", "datatype": "FLOAT", "mode": "REQUIRED"},
]
