steps:
  # Build the React app
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['ci']
  
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_API_URL=${_API_URL}'
  
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/agent-engine-ui:latest'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '-f'
      - 'Dockerfile'
      - '.'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/agent-engine-ui:latest']

images:
  - 'gcr.io/${PROJECT_ID}/agent-engine-ui:latest'

substitutions:
  _API_URL: ''
